# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build images
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build Api
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/src/BeboerWeb.Api/Dockerfile'
        tags: |
          api-$(tag)
          
    - task: Docker@2
    displayName: Build Mvc
    inputs:
      command: build
      dockerfile: '$(Build.SourcesDirectory)/src/BeboerWeb.Mvc/Dockerfile'
      tags: |
        mvc-$(tag)
